### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by D-Tasker207**
Fixed typo in readme

### CODE REVIEW

**Comment by Electromaster232** [comment]
Unfortunately this change is out-of-scope for this project, you'll need to write a working group proposal and get at least 50% approval before this can be implemented.

**Comment by D-Tasker207** [comment]
OP doesn't have the juevos to merge the pull request

**Comment by Electromaster232** [comment]
I see you have juevos of steel, I have no choice but to merge this

**Comment by D-Tasker207** [comment]
I ran a proposal and got 100% approval with myself, i think this should
demonstrate overwhelming support for this feature

**Pull request merged**
